# basic parameters
dataroot = 'datasets/summer2winter'
save_dir = 'models/checkpoints/'
isTrain = False
# model parameters
input_nc = 3
output_nc = 3
epoch = 90
# dataset parameters
preprocess = 'resize'
load_size = 256
batch_size = 1
# additional parameters
verbose = False